name: flutter_gokwik
description: A flutter plugin to integrate GoKwik's Flutter SDK.
version: 0.0.1
homepage: https://github.com/GoKwik/flutter-sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  eventify: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gokwik.flutter
        pluginClass: FlutterGokwikPlugin
      ios:
        pluginClass: FlutterGokwikPlugin

  uses-material-design: true
  assets:
    - assets/ic_whatsapp.png

